In [2]:
!pip install numpy

You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [3]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]

In [4]:
import numpy as np

In [5]:
np_height= np.array(height)

In [6]:
print(np_height)

[ 1.73  1.68  1.71  1.89  1.79]


In [7]:
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

In [8]:
np_weight=np.array(weight)

In [33]:
bmi=np_weight / np_height ** 2

In [34]:
print(bmi)

[ 21.85171573  20.97505669  21.75028214  24.7473475   21.44127836]


In [35]:
 array= [1,2,3]

In [36]:
np_array=np.array(array)

In [37]:
print(array+array)

[1, 2, 3, 1, 2, 3]


In [38]:
print(np_array+np_array)

[2 4 6]


In [39]:
print(bmi>23)

[False False False  True False]


In [40]:
print(bmi[bmi>23])

[ 24.7473475]
